### ISSUE TITLE
Crash when answering Y to exclude domains

### ISSUE THREAD

**Issue by markphelps** [StevenBlack/hosts#126]
Running `$ python updateHostsFile.py` on OS X.
Script crashes when answering 'Y' to the question 'Do you want to exclude any domains?'

```
Do you want to exclude any domains?
For example, hulu.com video streaming must be able to access its tracking and ad servers in order to play video. [Y/n] Y
Traceback (most recent call last):
  File "updateHostsFile.py", line 549, in <module>
    main()
  File "updateHostsFile.py", line 133, in main
    promptForExclusions()
  File "updateHostsFile.py", line 168, in promptForExclusions
    displayExclusionOptions()
  File "updateHostsFile.py", line 195, in displayExclusionOptions
    for exclusionOption in settings["common_exclusions"]:
KeyError: u'common_exclusions'
```

```
$ python --version
Python 2.7.11
```

Also tried using python3, same results.
```
$ python3 --version
Python 3.5.1
```

System Info:

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65
```

`Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`

**Comment by StevenBlack** [comment]
Nice report @markphelps!
