### ISSUE TITLE
Docker and WSL issues on Windows after running disable-dnscache-service-win.cmd

### ISSUE THREAD

**Issue by fuzzyBatman** [StevenBlack/hosts#1703]
Not fully sure if I should post this here

Does anyone else face issues with docker on windows after adding a hosts file and running _disable-dnscache-service-win.cmd_?

![error](https://user-images.githubusercontent.com/5787026/124358419-78484b00-dc20-11eb-99a3-d336dc75ab64.png)

Details:
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\User\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The RPC server is unavailable.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

**Comment by StevenBlack** [comment]
Hi Satyajith @fuzzyBatman, interesting.

Are there any hosts in a Windows Docker that we should be carrying in our base list?  I don't have any experience with Windows Docker. I hope someone can provide insight...

**Comment by dnmTX** [comment]
@fuzzyBatman maybe you can ask first at the source: [docker/for-win](https://github.com/docker/for-win/issues).
Much bigger chances to get some answers,who knows,could be resolution as well 👍

**Comment by fuzzyBatman** [comment]
I searched a bit and noticed that a lot of users reported "Enabling DNS client fixed the issue".

This applies even for Windows Subsystem for Linux (WSL). I could not get it running until I enabled the DNS client.

**Comment by dnmTX** [comment]
If the DNS client doesn't give you any troubles when adding the hosts from here,why would you disable it on the first place?

**Comment by fuzzyBatman** [comment]
It does give me issues.

A service called `Service Host: DNS Client` activates and renders my computer unusable for up to 10 minutes. And this happens many times in the same session.

**Comment by StevenBlack** [comment]
Thanks Satyajith @fuzzyBatman. This appears to be out of scope for this project, so I'm closing this issue now.
