### ISSUE TITLE
Problems with Debian Sid

### ISSUE THREAD

**Issue by lrfinotti** [StevenBlack/hosts#192]
I have two systems running Debian Sid in which the scripts worked perfectly, but (more or less) recently, both stopped working, but with different errors. 

``` 
$ update_hosts 
M       data/StevenBlack/hosts
M       data/malwaredomainlist.com/hosts
M       data/mvps.org/hosts
M       data/someonewhocares.org/hosts
M       data/yoyo.org/hosts
M       hosts
M       readme.md
Your branch is up-to-date with 'origin/master'.

Do you want to update all data sources? [Y/n] y
Updating source /root/hosts/data/mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source /root/hosts/data/someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Updating source /root/hosts/data/yoyo.org from http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source /root/hosts/data/malwaredomainlist.com from http://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source /root/hosts/data/StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source /root/hosts/data/adaway.org from http://adaway.org/hosts.txt
Problem getting file:  http://adaway.org/hosts.txt
Traceback (most recent call last):
  File "/root/hosts/updateHostsFile.py", line 384, in <module>
    main()
  File "/root/hosts/updateHostsFile.py", line 93, in main
    promptForUpdate()
  File "/root/hosts/updateHostsFile.py", line 107, in promptForUpdate
    updateAllSources()
  File "/root/hosts/updateHostsFile.py", line 176, in updateAllSources
    updatedFile = updatedFile.replace('\r', '') #get rid of carriage-return symbols
AttributeError: 'NoneType' object has no attribute 'replace'
```
and

```
$ update_hosts 
M       data/StevenBlack/hosts
M       data/malwaredomainlist.com/hosts
M       data/mvps.org/hosts
M       data/someonewhocares.org/hosts
M       data/yoyo.org/hosts
M       hosts
M       readme.md
M       updateHostsFile.py
Your branch is up-to-date with 'origin/master'.

Do you want to update all data sources? [Y/n] y
Updating source yoyo.org from http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source adaway.org from http://adaway.org/hosts.txt
Traceback (most recent call last):
  File "/root/hosts/updateHostsFile.py", line 312, in <module>
    main()
  File "/root/hosts/updateHostsFile.py", line 41, in main
    promptForUpdate()
  File "/root/hosts/updateHostsFile.py", line 54, in promptForUpdate
    updateAllSources()
  File "/root/hosts/updateHostsFile.py", line 120, in updateAllSources
    updatedFile = urllib2.urlopen(updateURL)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```
In this last one, I did check that I can access `http://pgl.yoyo.org/adservers/serverlist.php`.

Any help would be greatly appreciated.

**Comment by StevenBlack** [comment]
Are you using a (very) old version?  The [current line #384 in updateHostsFile.py](https://github.com/StevenBlack/hosts/blob/9d7cd2514455d0d978572901a326c55eb8552a17/updateHostsFile.py#L384) isn't prone to erroring like this.

Same can be said for [line #312](https://github.com/StevenBlack/hosts/blob/9d7cd2514455d0d978572901a326c55eb8552a17/updateHostsFile.py#L312).

**Comment by lrfinotti** [comment]
OK, I thought I was under the newest version, as my "update_hosts" scrip started with `git checkout` and as you can see above, it seemed to indicate it was up to date:

```
$ update_hosts 
M       data/StevenBlack/hosts
M       data/malwaredomainlist.com/hosts
M       data/mvps.org/hosts
M       data/someonewhocares.org/hosts
M       data/yoyo.org/hosts
M       hosts
M       readme.md
M       updateHostsFile.py
Your branch is up-to-date with 'origin/master'.
``` 
I guess I need to look up how to make sure I update to the newest version before running the script...  Sorry for the noise and thanks for the support!
