### ISSUE TITLE
updateHostsFile.py gets stuck in a loop when run from my home directory

### ISSUE THREAD

**Issue by seaside98** [StevenBlack/hosts#241]
I'm not entirely sure what the problem is here, it is possible that I have recursive symlinks somewhere in my home directory structure. When I run ```python3 /path/to/hosts/updateHostsFile.py -rafe fakenews gambling social``` in my home directory (```/Users/seaside98```), the program gets stuck in a infinite loop and doesn't print anything. 

MacOS 10.12.2
Python 3.5.0

The output when I ```^C```:
```
Traceback (most recent call last):
  File "/path/to/hosts/updateHostsFile.py", line 580, in <module>
    main()
  File "/path/to/hosts/updateHostsFile.py", line 140, in main
    promptForUpdate()
  File "/path/to/hosts/updateHostsFile.py", line 172, in promptForUpdate
    updateAllSources()
  File "/path/to/hosts/updateHostsFile.py", line 250, in updateAllSources
    allsources = recursiveGlob("*", settings["sourcedatafilename"])
  File "/path/to/hosts/updateHostsFile.py", line 551, in recursiveGlob
    return glob(stem + "/**/" + filepattern, recursive=True)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 103, in glob2
    yield from _rlistdir(dirname)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 121, in _rlistdir
    for y in _rlistdir(path):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/glob.py", line 122, in _rlistdir
    yield os.path.join(x, y)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/posixpath.py", line 82, in join
    if b.startswith(sep):
KeyboardInterrupt
```

**Comment by seaside98** [comment]
Closing as this is more an issue with python and my directory setup than anything most users would ever encounter.
