### ISSUE TITLE
Unreachable data sources should not crash updateHostsFile.py

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#26]
Please add exception for offline pages during update proccess. 

When I launched python2 updateHostsFile.py command and script stuck on trying download update file from http://someonewhocares.org/hosts/zero/hosts I have:

```
[tomasz@arch hosts]$ python2 updateHostsFile.py 
Do you want to update all data sources? [Y/n] Y
Updating source yoyo.org from http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source adaway.org from http://adaway.org/hosts.txt
Updating source mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source StevenBlack from https://raw.github.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Traceback (most recent call last):
  File "updateHostsFile.py", line 312, in <module>
    main()
  File "updateHostsFile.py", line 41, in main
    promptForUpdate()
  File "updateHostsFile.py", line 54, in promptForUpdate
    updateAllSources()
  File "updateHostsFile.py", line 120, in updateAllSources
    updatedFile = urllib2.urlopen(updateURL)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by FadeMind** [comment]
Temporary solution is changing URL in a file from default to https://pastebin.com/raw.php?i=KNKAzUrG
(it is my own pastebin copy of original file http://someonewhocares.org/hosts/zero/hosts. 

BTW. http://mvpshostsnews.blogspot.com/2015/09/mvps-hosts-file-update-september-18-2015.html

Working like a charm.

**Comment by StevenBlack** [comment]
Hi @FadeMind thanks for the suggestion.  I agree, there should be error handling here.

It looks like the link is working now; I just updated the data from sources, and created a new amalgamated hosts file, without issues.
