### ISSUE TITLE
Updating fails (OSX 10.11.6 - Python 2.7.10)

### ISSUE THREAD

**Issue by carmeloamg** [StevenBlack/hosts#266]
I found this error every time I try to update the data sources. The files are unmodified and updated. Not skills enough to try to fix but hope reporting helps improve the tool:

_Last login: Sun Mar 19 11:15:32 on ttys000
MacBook-de-Carmelo:~ Carmelo$ python --version
Python 2.7.10
MacBook-de-Carmelo:~ Carmelo$ python /Applications/hosts-master/updateHostsFile.py 
Do you want to update all data sources? [Y/n] y
Traceback (most recent call last):
  File "/Applications/hosts-master/updateHostsFile.py", line 582, in <module>
    main()
  File "/Applications/hosts-master/updateHostsFile.py", line 142, in main
    promptForUpdate()
  File "/Applications/hosts-master/updateHostsFile.py", line 174, in promptForUpdate
    updateAllSources()
  File "/Applications/hosts-master/updateHostsFile.py", line 256, in updateAllSources
    updateURL  = updateData["url"]
KeyError: u'url'
MacBook-de-Carmelo:~ Carmelo$_

Best regards.

**Comment by gfyoung** [comment]
Hmm...not really much to work from here.  Some print statements around the `updateURL` statement (e.g. the value of `source` and other variables in the code) might be useful.

**Comment by MacsInSpace** [comment]
I'm also having this issue on MacOS 10.13.3 - Python version 2.7.10 - Pip - version 9.0.1
I'm happy to run any extra options for debugging to troubleshoot this.
I'm more than happy on the command line but only have a basic python knowledge.

`sudo python /Users/user/Downloads/hosts-master/updateHostsFile.py
Do you want to update all data sources? [Y/n] Y
Traceback (most recent call last):
  File "/Users/user/Downloads/hosts-master/updateHostsFile.py", line 1416, in <module>
    main()
  File "/Users/user/Downloads/hosts-master/updateHostsFile.py", line 167, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "/Users/user/Downloads/hosts-master/updateHostsFile.py", line 605, in update_all_sources
    update_url = update_data["url"]
KeyError: u'url'
`
Craig.

**Comment by funilrys** [comment]
Hi Steve @StevenBlack,
This one can be closed.
