### ISSUE TITLE
Unable to update hosts file

### ISSUE THREAD

**Issue by bisherbas** [StevenBlack/hosts#414]
Linux Bash on Windows 10

```$ python makeHosts.py
Updating source ./data/adaway.org from https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
Updating source ./data/add.2o7Net from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
Updating source ./data/add.Dead from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
Updating source ./data/add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Updating source ./data/add.Spam from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
Updating source ./data/Badd-Boyz-Hosts from https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
Updating source ./data/KADhosts from https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
Updating source ./data/malwaredomainlist.com from https://www.malwaredomainlist.com/hostslist/hosts.txt
Updating source ./data/mvps.org from http://winhelp2002.mvps.org/hosts.txt
Updating source ./data/someonewhocares.org from http://someonewhocares.org/hosts/zero/hosts
Updating source ./data/SpotifyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/SpotifyAds/hosts
Updating source ./data/StevenBlack from https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
Updating source ./data/tyzbit from https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts
Updating source ./data/UncheckyAds from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
Updating source ./data/yoyo.org from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
Updating source ./extensions/fakenews from https://raw.githubusercontent.com/marktron/fakenews/master/fakenews
Updating source ./extensions/gambling from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts
Updating source ./extensions/porn/clefspeare13 from https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts
Updating source ./extensions/porn/sinfonietta from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
Updating source ./extensions/porn/sinfonietta-snuff from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/snuff-hosts
Updating source ./extensions/social from https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
==>0.0.0.0 #[server<==
==>0.0.0.0 130.211.230.53<==
Traceback (most recent call last):
  File "updateHostsFile.py", line 1276, in <module>
    main()
  File "updateHostsFile.py", line 189, in main
    sourcesdata=sources_data)
  File "updateHostsFile.py", line 849, in update_readme_data
    readme_data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Failed to update hosts file
Traceback (most recent call last):
  File "updateReadme.py", line 143, in <module>
    main()
  File "updateReadme.py", line 33, in main
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

**Comment by ScriptTiger** [comment]
Have you tried installing Python for Windows? If you are having trouble with the Linux subsystem for Windows 10, they also have their own GitHub for support:
https://github.com/Microsoft/BashOnWindows/issues
I don't think we can provide support for that, especially since it's still officially a beta and there are bound to be problems with it anyway. You can also try something like Cygwin. However, projects like the Linux subsystem, Cygwin, and MinGW are not a replacement for an actual Linux system, but do try to provide a certain level of compatibility for certain things. Python, on the other hand, is a standardized language and you can find packages for it designed to be installed on a Windows system.

**Comment by StevenBlack** [comment]
Hi Bish @bisherbas – what version of Python are you running here?

**Comment by bisherbas** [comment]
Python v2.7

I was able to update the hosts file both on MinGW and Linux Bash on Win10 just a few weeks ago. So I thought the error is related to the hosts code itself.

**Comment by rautamiekka** [comment]
^
>Python v2.7

2.7.0 ?

**Comment by bisherbas** [comment]
Yes. 2.7.0.

**Comment by ScriptTiger** [comment]
I do use the Linux subsystem as well, but I can't begin to help troubleshoot it for the reasons I stated above. Hopefully one of these other guys can stick with it and help you out. However, what is the ultimate purpose you are going for? If you are just trying to keep your hosts file up to date, have you tried looking into the Windows auto-updater?
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

**Comment by bisherbas** [comment]
AutoUpdate solves the original problem. Thanks.
