### ISSUE TITLE
[Python3] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 27: ordinal not in range(128)

### ISSUE THREAD

**Issue by FadeMind** [StevenBlack/hosts#494]
```
$ python3 updateHostsFile.py -a
Updating source data/add.Risk from https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
Traceback (most recent call last):
  File "updateHostsFile.py", line 1371, in <module>
    main()
  File "updateHostsFile.py", line 161, in main
    update_all_sources(source_data_filename, settings["hostfilename"])
  File "updateHostsFile.py", line 591, in update_all_sources
    update_data = json.load(update_file)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 27: ordinal not in range(128)
```

During using Python2 went fine except failed download
```
Error in updating source:  http://someonewhocares.org/hosts/zero/hosts
```
hosts file is EMPTY in `data/someonewhocares.org/` directory.

MOST Weird is that http://someonewhocares.org/hosts/zero/hosts is VALID (but not downloaded).

CC @StevenBlack

**Comment by funilrys** [comment]
Can you try to patch #481 in order to test if it is a possible fix  ?

**Comment by FadeMind** [comment]
See https://github.com/StevenBlack/hosts/pull/481#discussion_r167424332

**Comment by Atavic** [comment]
Also see: https://github.com/StevenBlack/hosts/issues/420

**Comment by FadeMind** [comment]
@StevenBlack closing casue dupe.
