### ISSUE TITLE
Unable to run updateHostsFile.py - Ubuntu Xenial

### ISSUE THREAD

**Issue by crmlt** [StevenBlack/hosts#690]
I wonder why I'm currently unable to run the script:

```
$ python2 updateHostsFile.py -a -r --extensions fakenews porn gambling
  File "updateHostsFile.py", line 1513, in <module>
    main()
  File "updateHostsFile.py", line 187, in main
    merge_file = create_initial_file()
  File "updateHostsFile.py", line 640, in create_initial_file
    write_data(merge_file, start + curFile.read() + end)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19107:
ordinal not in range(128)
```

```
$ python3 updateHostsFile.py -a -r --extensions fakenews porn gambling
Traceback (most recent call last):
  File "updateHostsFile.py", line 26, in <module>
    import lxml  # noqa: F401
ImportError: No module named 'lxml'
```
(python-lxml already installed)

**Comment by hughgrigg** [comment]
Try installing `python3-lxml`.

**Comment by StevenBlack** [comment]
Thanks Nissar @funilrys!

Closing.
