### ISSUE TITLE
updateHostsFile crashes when run under path contains CJK characters

### ISSUE THREAD

**Issue by Vdragon** [StevenBlack/hosts#81]
## Console output

```
~/工作空間/第三方專案/Amalgamated hosts file$ python updateHostsFile.py --help
Traceback (most recent call last):
  File "updateHostsFile.py", line 78, in <module>
    DATA_PATH           = os.path.join(BASEDIR_PATH, 'data')
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 14: ordinal not in range(128)
```
### Operating System

Ubuntu 15.10 AMD64
### Python

2.7.10
### Amalgamated hosts file

commit 231dc436
### Locale

```
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_HK:zh_CN:en_US:en
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC=zh_TW.UTF-8
LC_TIME=zh_TW.UTF-8
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY=zh_TW.UTF-8
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER=zh_TW.UTF-8
LC_NAME=zh_TW.UTF-8
LC_ADDRESS=zh_TW.UTF-8
LC_TELEPHONE=zh_TW.UTF-8
LC_MEASUREMENT=zh_TW.UTF-8
LC_IDENTIFICATION=zh_TW.UTF-8
LC_ALL=
```

**Comment by StevenBlack** [comment]
Thanks for reporting this @Vdragon.  Excellent bug report.

**Comment by Vdragon** [comment]
I cloned the latest revision and the issue is no longer reproducible, great job!
