### ISSUE TITLE
error creating hosts file

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [StevenBlack/hosts#91]
i just did a `git clone` and tried to use the script and got this:

```
Traceback (most recent call last):
  File "updateHostsFile.py", line 446, in <module>
    main()
  File "updateHostsFile.py", line 112, in main
    removeOldHostsFile()
  File "updateHostsFile.py", line 374, in removeOldHostsFile
    shutil.copyfile(oldFilePath, backupFilePath) # make a backup copy, marking the date in which the list was updated
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 22] invalid mode ('wb') or filename: u'D:\\Program Files\\hosts\\hosts-02/21/16 18:51:34'
```

it ends up creating a 0 byte `hosts` file

Python 2.7.10
Windows 7 [x64]

**Comment by StevenBlack** [comment]
@berrythesoftwarecodeprogrammar can you please try again with the latest version?

I replaced [line 374](https://github.com/StevenBlack/hosts/commit/e8033bff7281ab34d458290cf7b62584d2fc0ed0) in the hopes this'll work for you under Windows.

**Comment by berrythesoftwarecodeprogrammar** [comment]
nop

```
Traceback (most recent call last):
  File "updateHostsFile.py", line 446, in <module>
    main()
  File "updateHostsFile.py", line 112, in main
    removeOldHostsFile()
  File "updateHostsFile.py", line 374, in removeOldHostsFile
    shutil.copy(oldFilePath, backupFilePath) # make a backup copy, marking the date in which the list was updated
  File "C:\Python27\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\a\\wrz\\hosts\\asd\\hosts\\hosts-02/22/16 10:54:08'
```

**Comment by StevenBlack** [comment]
Can you do me a favor @berrythesoftwarecodeprogrammar?

Can you try in a folder that doesn't have a space in its name?  Because Windows, you know, is truly a brain-dead OS in that way.

**Comment by berrythesoftwarecodeprogrammar** [comment]
that last example was in a directory without spaces. i tried again now in `C:\hosts\`:
```
Traceback (most recent call last):
  File "updateHostsFile.py", line 446, in <module>
    main()
  File "updateHostsFile.py", line 112, in main
    removeOldHostsFile()
  File "updateHostsFile.py", line 374, in removeOldHostsFile
    shutil.copy(oldFilePath, backupFilePath) # make a backup copy, marking the date in which the list was updated
  File "C:\Python27\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\hosts\\hosts-02/22/16 11:53:34'
```

windows filenames cant have `/` or `:`

**Comment by StevenBlack** [comment]
Doh!  Of course.  OK, I'm an idiot.

Fixed now.  Thanks for your patience!
