### ISSUE TITLE
error creating hosts file on CentOS

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [StevenBlack/hosts#95]
```
OK, we'll only exclude domains in the whitelist.
Traceback (most recent call last):
  File "updateHostsFile.py", line 468, in <module>
    main()
  File "updateHostsFile.py", line 126, in main
    updateReadme(numberOfRules)
  File "updateHostsFile.py", line 366, in updateReadme
    out.write(line.replace('@NUM_ENTRIES@', "{:,}".format(numberOfRules)))
ValueError: zero length field name in format
```

CentOS 6.7
Python 2.6.6

**Comment by berrythesoftwarecodeprogrammar** [comment]
fixed by installing python2.7

https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4
